from pydantic import BaseModel, Field
from typing import Annotated, Literal, Optional
from operator import add


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the agent")
    user_question: str = Field(default="", description="The original question asked by the user")
    curated_ques: str = Field(default="", description="Curated user question")
    prompt_query_context: str = Field(default="", description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query: str = Field(default="", description="The SQL query generated by the agent based on the curated question and prompt context")
    is_safe: Literal["Yes", "No"] = Field(default="No", description="Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(default="", description="Comments regarding the safety of the generated SQL query")
    sql_query_execution_result: str = Field(default="", description="The result of executing the generated SQL query on the database")
    sql_retry_count: int = Field(default=0, description="Count of SQL reflection retries on execution failure")
    sql_error_message: str = Field(default="", description="Error message captured from database execution failure")
    chart_image_path: str = Field(default="", description="Path to generated visualization chart PNG image")
    final_answer: str = Field(default="", description="The final answer generated by the agent")


class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")


class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the ETL agent")


class VizAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the Viz agent")
    chart_code: str = Field(default="", description="Generated Matplotlib/Seaborn python code")
    chart_image_path: str = Field(default="", description="File path of saved PNG chart")
    summary: str = Field(default="", description="Natural language summary of chart")


class RouterSchema(BaseModel):
    answer: Literal["sql", "etl", "viz"] = Field(..., description="Indicates whether the user's question is related to SQL, ETL, or Visualization operations")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")


class DataAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the Data agent")
    route_response: str = Field(default="", description="The response from the router indicating whether to route to SQL, ETL, or VIZ operations")